# Generated by Django 2.0 on 2018-10-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PinModule',
            fields=[
                ('pin_id', models.AutoField(primary_key=True, serialize=False)),
                ('pinName', models.CharField(max_length=15)),
                ('pinNo', models.IntegerField()),
                ('action', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='pinmodule',
            name='Reg_Module_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestService.Register'),
        ),
    ]
