# Generated by Django 2.0 on 2018-11-24 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PinModule',
            fields=[
                ('pin_id', models.AutoField(primary_key=True, serialize=False)),
                ('pin_name', models.CharField(max_length=15)),
                ('pin_no', models.IntegerField()),
                ('module_type', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'RestService_pinmodule',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial', models.CharField(max_length=15)),
                ('module_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'RestService_register',
            },
        ),
        migrations.AddField(
            model_name='pinmodule',
            name='reg_module_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestService.Register'),
        ),
    ]
