# Generated by Django 2.0 on 2018-10-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestService', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorModule',
        ),
    ]
